[package]
name = "embedded_holochain_runner"
version = "0.0.103"
authors = ["Connor Turland <connor@sprillow.com>"]
edition = "2018"

[lib]

[dependencies]
# use whatever hdk uses
serde = "*"
futures = "0.3.1"
human-panic = "1.0.3"
# use whatever hdk uses
tracing = "*"
tokio = { version = "1.3", features = [ "full" ]}
holochain_util = "0.0.3"
holochain_p2p = "0.0.3"
holochain_types = "0.0.3"
holochain_zome_types = "0.0.5"
holochain_keystore = "0.0.3"
holochain = "0.0.103"
hdk = "0.0.103"

[patch.crates-io]
rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }