[package]
name = "embedded_holochain_runner"
version = "0.0.1"
authors = ["Connor Turland <connor@sprillow.com>"]
edition = "2018"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# use whatever hdk uses
serde = "*"
futures = "0.3.1"
human-panic = "1.0.3"
# use whatever hdk uses
tracing = "*"
tokio = { version = "1.3", features = [ "full" ]}
tokio_helper = {git = "https://github.com/holochain/holochain.git", branch = "2021-05-12-deepkey-tweaks", package = "tokio_helper"}
holochain_p2p = {git = "https://github.com/holochain/holochain.git", branch = "2021-05-12-deepkey-tweaks", package = "holochain_p2p"}
holochain_types = {git = "https://github.com/holochain/holochain.git", branch = "2021-05-12-deepkey-tweaks", package = "holochain_types"}
holochain_zome_types = {git = "https://github.com/holochain/holochain.git", branch = "2021-05-12-deepkey-tweaks", package = "holochain_zome_types"}
holochain_keystore = {git = "https://github.com/holochain/holochain.git", branch = "2021-05-12-deepkey-tweaks", package = "holochain_keystore"}
holochain = {git = "https://github.com/holochain/holochain.git", branch = "2021-05-12-deepkey-tweaks", package = "holochain", features = []}
hdk = { git = "https://github.com/holochain/holochain", branch = "2021-05-12-deepkey-tweaks", package = "hdk" }

[patch.crates-io]
rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }